[project]
name = "snakemake-tutorial"
version = "0.1.0"
description = "Learning snakemake with a tutorial"
authors = ["Nicholson <nicholson.tom.n@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64"]

[tasks]
snakemake = "snakemake"
dryrun = "snakemake -np"
dag = "snakemake --dag | dot -Tsvg"

[dependencies]
python = ">=3.12.4,<4"
snakemake = ">=8.16.0,<9"
jinja2 = ">=3.1.4,<4"
matplotlib = ">=3.9.1,<4"
graphviz = ">=11.0.0,<12"
bcftools = ">=1.20,<2"
samtools = ">=1.20,<2"
pygments = ">=2.18.0,<3"

[activation]
env = { PATH = "/Users/nicth99p/bin/third-party/bwa-0.7.18/:$PATH" }

[pypi-dependencies]
pysam = ">=0.22.1, <0.23"
